package com.github.esrrhs.majiang_algorithm;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Replays go/testdata/parity_cases.txt against the Java implementation.
 * The fixture is generated by ParityDump and shared with go parity_test.go;
 * both languages must reproduce every field exactly.
 */
public class ParityFixtureTest
{
	private static final String[] FIXTURE_PATHS = new String[]
	{ "../go/testdata/parity_cases.txt", "go/testdata/parity_cases.txt", "testdata/parity_cases.txt" };

	private static List<String> lines;

	@BeforeAll
	public static void setUp() throws Exception
	{
		File file = null;
		for (String path : FIXTURE_PATHS)
		{
			File f = new File(path);
			if (f.exists())
			{
				file = f;
				break;
			}
		}
		Assumptions.assumeTrue(file != null, "parity fixture not found, skipping");

		lines = new ArrayList<>();
		try (BufferedReader r = new BufferedReader(
				new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8)))
		{
			String line;
			while ((line = r.readLine()) != null)
			{
				if (!line.isEmpty() && !line.startsWith("#"))
				{
					lines.add(line);
				}
			}
		}
		HuUtil.load();
		AIUtil.load();
	}

	@Test
	public void testParityFixture()
	{
		assertTrue(lines.size() > 0);
		int caseIndex = 0;
		for (String line : lines)
		{
			String[] f = line.split("\\|", -1);
			assertEquals(13, f.length, "field count case " + caseIndex);

			List<Integer> hand = MaJiangDef.stringToCards(f[0]);
			int gui = Integer.parseInt(f[1]);
			List<Integer> guiList = Arrays.asList(gui);
			int chiCard = Integer.parseInt(f[8]);

			assertEquals(Integer.parseInt(f[2]), HuUtil.isHu(hand, gui) ? 1 : 0, "isHu case " + caseIndex);
			assertEquals(Integer.parseInt(f[3]), HuUtil.isHuExtra(hand, guiList, 0) ? 1 : 0,
					"isHuExtra case " + caseIndex);
			assertEquals(f[4], MaJiangDef.cardsToString(HuUtil.isTing(hand, gui)), "isTing case " + caseIndex);
			assertEquals(f[5], MaJiangDef.cardsToString(HuUtil.isTingExtra(hand, guiList)),
					"isTingExtra case " + caseIndex);
			assertEquals(Double.parseDouble(f[6]), AIUtil.calc(hand, guiList), 0.0, "calc case " + caseIndex);
			assertEquals(Integer.parseInt(f[7]), AIUtil.outAI(hand, guiList), "outAI case " + caseIndex);
			assertEquals(f[9], MaJiangDef.cardsToString(AIUtil.chiAI(hand, guiList, chiCard)),
					"chiChoices case " + caseIndex);
			assertEquals(Integer.parseInt(f[10]), AIUtil.chiAI(hand, guiList, chiCard, chiCard - 1,
					chiCard + 1) ? 1 : 0, "chiBool case " + caseIndex);
			assertEquals(Integer.parseInt(f[11]), AIUtil.pengAI(hand, guiList, chiCard, 0.d) ? 1 : 0,
					"peng case " + caseIndex);
			assertEquals(Integer.parseInt(f[12]), AIUtil.gangAI(hand, guiList, chiCard, 1.d) ? 1 : 0,
					"gang case " + caseIndex);
			caseIndex++;
		}
		System.out.println("[PARITY] replayed " + caseIndex + " cases against Java implementation");
	}
}
